### ISSUE TITLE
Error: Cannot find module '@graphile/postgis'

### ISSUE THREAD

**Issue by OGrigorios** [graphile/postgis#55]
Deploying postgraphile-cli in a Dockerfile and trying to enable the postgis plugin throws me the following error:

```
graphql_container_infrastructure  | Node.js v20.0.0
graphql_container_infrastructure  | Failed to load plugin ' @graphile/postgis'
graphql_container_infrastructure  | /usr/local/lib/node_modules/postgraphile/build/postgraphile/cli.js:303
graphql_container_infrastructure  |             throw e;
graphql_container_infrastructure  |             ^
graphql_container_infrastructure  |
graphql_container_infrastructure  | Error: Cannot find module ' @graphile/postgis'
graphql_container_infrastructure  | Require stack:
graphql_container_infrastructure  | - /usr/local/lib/node_modules/postgraphile/build/postgraphile/cli.js
graphql_container_infrastructure  | - /usr/local/lib/node_modules/postgraphile/cli.js
graphql_container_infrastructure  |     at Module._resolveFilename (node:internal/modules/cjs/loader:1082:15)
graphql_container_infrastructure  |     at Module._load (node:internal/modules/cjs/loader:928:27)
graphql_container_infrastructure  |     at Module.require (node:internal/modules/cjs/loader:1149:19)
graphql_container_infrastructure  |     at require (node:internal/modules/helpers:121:18)
graphql_container_infrastructure  |     at /usr/local/lib/node_modules/postgraphile/build/postgraphile/cli.js:298:20
graphql_container_infrastructure  |     at Array.map (<anonymous>)
graphql_container_infrastructure  |     at loadPlugins (/usr/local/lib/node_modules/postgraphile/build/postgraphile/cli.js:281:18)
graphql_container_infrastructure  |     at Object.<anonymous> (/usr/local/lib/node_modules/postgraphile/build/postgraphile/cli.js:358:23)
graphql_container_infrastructure  |     at Module._compile (node:internal/modules/cjs/loader:1267:14)
graphql_container_infrastructure  |     at Module._extensions..js (node:internal/modules/cjs/loader:1321:10) {
graphql_container_infrastructure  |   code: 'MODULE_NOT_FOUND',
graphql_container_infrastructure  |   requireStack: [
graphql_container_infrastructure  |     '/usr/local/lib/node_modules/postgraphile/build/postgraphile/cli.js',
graphql_container_infrastructure  |     '/usr/local/lib/node_modules/postgraphile/cli.js'
graphql_container_infrastructure  |   ]
graphql_container_infrastructure  | }
```

Here is the relevant Dockerfile:
```
FROM node:alpine
LABEL description="Instant high-performance GraphQL API for your PostgreSQL database https://github.com/graphile/postgraphile"

# Install PostGraphile and PostGraphile connection filter plugin
RUN npm install -g postgraphile
RUN npm install -g postgraphile-plugin-connection-filter
# RUN npm install -g @graphile/postgis

# RUN yarn add postgraphile
# RUN yarn add postgraphile-plugin-connection-filter
RUN yarn add @graphile/postgis

EXPOSE 5000
ENTRYPOINT ["postgraphile", "-n", "0.0.0.0"]
```

I have installed the extension via `RUN npm install -g @graphile/postgis` and appended the plugin to my `append-plugins` subcommand, in my docker compose file. I have been following this tutorial to set it all up: [Running PostGraphile in Docker](https://www.graphile.org/postgraphile/running-postgraphile-in-docker/#create-postgresql-container).
I also tried it with `yarn add @graphile/postgis` but this resulted in the error. Furthermore, installing all software via yarn in a dockerfile results in the postgraphile executable not being found by the container.

I am happy to supply more information when needed.

**Comment by OGrigorios** [comment]
I don't know why, but it is found now. I rebuilt my Dockerfile a dozen times before, but only after the most recent build it could be found. Maybe keep this issue open, since the next few days I will be experimenting with this plugin some more, and maybe I run into it again.

**Comment by benjie** [comment]
The error indicates you have a space at the beginning of your module name, seems it may have been a typo on the command line.

**Comment by benjie** [comment]
> `graphql_container_infrastructure  | Error: Cannot find module ' @graphile/postgis'`
